### PR TITLE
Categories

### PR DESCRIPTION
**Pull request by djfm**

### CODE REVIEW

**Comment by gabdara** [comment]
:+1: 
I have a little bit of OCD on that h1 class="h2" :smile:

**Comment by gabdara** [comment]
... that h1 class="h2"

**Comment by djfm** [comment]
Yes this is surely debatable, took the idea from here: http://www.stubbornella.org/content/2011/09/06/style-headings-using-html5-sections/

I think he makes a good point but I'm open to suggestions!

**Comment by gabdara** [comment]
The article has a valid point, but at the first glance it makes you raise an eyebrow :wink:

**Comment by kpodemski** [comment]
hehe, h1.h2, I don't like this :) and I don't know if it is good for SEO to have `<h1>Subcategories</h1>`, there is no value in this phrase for seo and it is not title for a page, IMO this should be consulted with some SEO specialist but in my opinion we should keep one `<h1>`, also, I don't know if `<section>` is good for product list, it should by `<article>`.

**Comment by djfm** [comment]
Honestly I don't know, SEO is not my strong suit. Most important thing is that the template is 30 lines long  so whatever the best practice is, it won't be hard to implement :)

**Comment by kpodemski** [comment]
Also, shall we use "miniature"? Maybe it should be... "thumbnail"? :) In back-office we can add "thumbnails" :D

**Comment by djfm** [comment]
Thought about it, but I think what we call thumbnails is just the pictures, this is a little bit different

**Comment by prestarocket** [comment]
Hello,
@djfm you are right for h1 and section : https://developer.mozilla.org/en/docs/Web/HTML/Sections_and_Outlines_of_an_HTML5_document :
Note: Each section can have its own heading hierarchy. Therefore, even a nested section can have an h1. See Defining Headings in HTML5.
But for product miniaure, i ll wrap each in article tag.

**Comment by djfm** [comment]
@kpodemski 

> You can add rel="nofollow", data-id-product="", data-id-product-attribute=""

done, thanks!

@prestarocket 

> But for product miniaure, i ll wrap each in article tag.

done, thanks!

**Comment by julienbourdeau** [comment]
@prestarocket : I'm really not a big fan of BEM syntax. Are you using it on a day-to-day basis ?

**Pull request merged**
