### PR TITLE
Updated product-prices template

### PR DESCRIPTION
**Pull request by mickaelandrieu**
This is a port from https://github.com/PrestaShop/PrestaShop/pull/9027

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
@PierreRambaud the build is broken, I try to relaunch it...

**Comment by mickaelandrieu** [comment]
@PierreRambaud this is not good, build sounds broken

```
The command "docker exec prestashop git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"" failed and exited with 126 during .
```

**Comment by PierreRambaud** [comment]
haha, look funny yes:
```php
PHP Fatal error:  Cannot redeclare class Symfony\Bundle\SwiftmailerBundle\Command\DebugCommand in /var/www/html/vendor/symfony/swiftmailer-bundle/Command/Command/DebugCommand.php on line 135
Fatal error: Cannot redeclare class Symfony\Bundle\SwiftmailerBundle\Command\DebugCommand in /var/www/html/vendor/symfony/swiftmailer-bundle/Command/Command/DebugCommand.php on line
```

**Comment by mickaelandrieu** [comment]
> PHP Fatal error:  Cannot redeclare class Symfony\Bundle\SwiftmailerBundle\Command\DebugCommand in /var/www/html/vendor/symfony/swiftmailer-bundle/Command/Command/DebugCommand.php on line 135

Yeah, it's linked to my update of template, 100% xD

**Comment by PierreRambaud** [comment]
It's your fault mate!!!

**Comment by Quetzacoalt91** [comment]
This PR cannot pass the tests because you didn't use your fork.

In this case, the env var `$TRAVIS_BRANCH` is not using the destination branch of the destination repository, but the source branch `lazy-loading`.

@mickaelandrieu, please recreate your PR by using changes from your fork.

**Comment by PierreRambaud** [comment]
This project is not maintained anymore by the core team. Theme improvements must be brought instead to the classic theme in the [PrestaShop repository](https://github.com/PrestaShop/PrestaShop).
Thanks for your understanding.

**Pull request closed without merging**
