### PR TITLE
fix webpack for use of npm run build

### PR DESCRIPTION
**Pull request by PowerMugen**
having only one output file to avoid error when building webpack

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi @PowerMugen,

Thanks for your contribution. Can you show the error you're fixing?

**Comment by PowerMugen** [comment]
The only issue with "npm run watch" is that I needed to do it every time I open the project. 
Current file has twice 

`output: {
 path: '../assets/js',
filename: 'theme.js'
},`

"npm run watch" work as intentend but "npm run build" failed and /assets/theme.js was emptied every time I open my project and I was forced to launch watch then make a modification in _dev/js/theme.js for my javascript to be written in /assets/js/theme.js

**Comment by gnujeremie** [comment]
Spent an entire morning trying to understand what was going on, finally found out it was this error. I opened #208 ; how is this pull request still opened after almost an entire year ?

**Comment by mickaelandrieu** [comment]
What do you think @eternoendless ?

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Looks good to me. Sorry about the delay!

We need to test run a build to see if this works as expected.

**Comment by smartdatasoft** [comment]
Please merge this, we have to re-do this work after download starter theme.

**Pull request merged**
