### PR TITLE
Directory structure proposal

### PR DESCRIPTION
**Pull request by julienbourdeau**
Here is what I think could be a good structure.
- Remember smarty will be secure by default in PrestaShop 1.7, so no need to use `|escape:'html':'UTF-8'` anymore.
- I moved data like `$language_code` or `$meta_title` into an array called `$page`. These data should always be defined (even if empty) then we don't need to have loads of `{if isset($meta_description) AND $meta_description}`
- We want to create as many blocks as possible (if it makes sense of course), cf. `head.tpl`.

The directory structure is open for discussion, **please leave your opinion**.

<table>
  <tr>
    <th width="50%">Current structure</th>
    <th width="50%">New Structure Proposal (not complete)</th>
  </tr>
  <tr>
<td>
<pre>
├── 404.tpl
├── address.tpl
├── addresses.tpl
├── authentication.tpl
├── best-sales.tpl
├── breadcrumb.tpl
├── category-cms-tree-branch.tpl
├── category-count.tpl
├── category-tree-branch.tpl
├── category.tpl
├── cms.tpl
├── config.rb
├── config.xml
├── contact-form.tpl
├── css
│   └── empty
├── discount.tpl
├── errors.tpl
├── fonts
│   ├── FontAwesome.otf
│   ├── fontawesome-webfont.eot
│   ├── fontawesome-webfont.svg
│   ├── fontawesome-webfont.ttf
│   ├── fontawesome-webfont.woff
│   ├── fontawesome-webfont.woff2
│   └── index.php
├── footer.tpl
├── global.tpl
├── guest-tracking.tpl
├── header.tpl
├── history.tpl
├── identity.tpl
├── img
│   └── emtpy
├── index.php
├── index.tpl
├── js
│   └── empty
├── layout.tpl
├── maintenance.tpl
├── manufacturer-list.tpl
├── manufacturer.tpl
├── mobile
│   ├── css
│   │   ├── autoload
│   │   │   └── index.php
│   │   └── index.php
│   ├── index.php
│   └── js
│       ├── autoload
│       │   └── index.php
│       └── index.php
├── my-account.tpl
├── nbr-product-page.tpl
├── new-products.tpl
├── order-address-advanced.tpl
├── order-address-multishipping-products.tpl
├── order-address-multishipping.tpl
├── order-address-product-line.tpl
├── order-address.tpl
├── order-carrier-advanced.tpl
├── order-carrier-opc-advanced.tpl
├── order-carrier.tpl
├── order-confirmation.tpl
├── order-detail.tpl
├── order-follow.tpl
├── order-opc-advanced.tpl
├── order-opc-new-account-advanced.tpl
├── order-opc-new-account.tpl
├── order-opc.tpl
├── order-payment-advanced.tpl
├── order-payment-classic.tpl
├── order-payment.tpl
├── order-return.tpl
├── order-slip.tpl
├── order-steps.tpl
├── pagination.tpl
├── password.tpl
├── preview.jpg
├── prices-drop.tpl
├── product-compare.tpl
├── product-list-colors.tpl
├── product-list.tpl
├── product-sort.tpl
├── product.tpl
├── products-comparison.tpl
├── restricted-country.tpl
├── sass
│   └── empty
├── scenes.tpl
├── search.tpl
├── shopping-cart-advanced.tpl
├── shopping-cart-product-line.tpl
├── shopping-cart.tpl
├── sitemap.tpl
├── store_infos.tpl
├── stores.tpl
├── supplier-list.tpl
└── supplier.tpl
</pre>
</td>
<td>
<pre>
├── CONTRIBUTING.md
├── README.md
├── assets
│   ├── css
│   │   └── theme.css
│   ├── fonts
│   ├── img
│   │   └── logo.png
│   └── js
├── config
└── templates
    ├── _partials
    │   ├── breadcrumb.tpl
    │   ├── footer.tpl
    │   ├── head.tpl
    │   ├── header.tpl
    │   └── pagination.tpl
    ├── address.tpl
    ├── cart.tpl
    ├── catalog
    │   ├── _partials
    │   │   ├── product-discount-table.tpl
    │   │   └── product-price.tpl
    │   └── product.tpl
    ├── customer
    │   ├── login.tpl
    │   ├── my-account.tpl
    │   └── register.tpl
    ├── errors
    │   ├── 404.tpl
    │   └── static
    │       ├── 500.html
    │       └── 503.html
    ├── home.tpl
    ├── layout.tpl
    └── list.tpl
</pre>
</td>
  </tr>
</table>

### CODE REVIEW

**Comment by kpodemski** [comment]
Ok, we have /assets/, what about overriding files for modules? it will be in /assets/css/modules? or /override/modules/js/? I think now it is a time to simplify structure for overriding where we don't need to have:
theme/js/modules/something/file.js
theme/css/modules/something/css.js

but for example:
override/modules/(views ?)/js/
override/modules/(views ?)/css/
override/modules/(views ?)/templates/

?

Edit: I like that smarty variables will be escaped, however how can we prevent escape? for example we have content manager where we need to have exact html as in module, can we simply use "unescape"?

**Comment by Shudrum** [comment]
Why __partials_ instead of _partials_ ? This is just ugly ^^

We should be consistent.

**Comment by gabdara** [comment]
To override modules I suggest only folder modules (not override/modules, because in folder override from theme we can't override something else) in which to have the option to override all the files from folder views (except folder admin)

**Comment by kpodemski** [comment]
@gabdara agree, for me it is good to simply have one place for all files to make this cleaner

**Comment by julienbourdeau** [comment]
@kpodemski You're right for hook calls, I changed it.

@Shudrum We'd like to split the templates into subfolders according to their role: customer, cms, shopping cart... I like that you can see the `_partials` folder is not the same as `customer` folder.

**Comment by gRoussac** [comment]
Hi,

"Customer" folder is not a generic name, and an address (address.tpl) is not a customer.

Regards

**Comment by kpodemski** [comment]
product.tpl, category.tpl etc. to /catalog/? cart.tpl etc. to /order/?

**Comment by julienbourdeau** [comment]
## About module overrides

We are considering changing the way it works. Ideally **you will only be able to override the template** (.tpl file).
- If you want to change the CSS, you shouldn't override the whole file. Your `themes/yourtheme/assets/css/theme.css` can define the required the styles in order to override `modules/blocktest/css/main.css` styles.
- JavaScript is for logic, your theme probably shouldn't modify this behavior.

Again: it's open for discussion.

**Comment by kpodemski** [comment]
I agree with having theme.css, it will be pefect if PrestaShop can look for theme.css and if this file exists it is loaded _after_ primary module CSS file.

For javascript - maybe, maybe it is for logic but still sometimes we need to change - for example owlCarousel 1 to owlCarousel 2, one library to another, change selectors etc.

**Comment by julienbourdeau** [comment]
I updated the directory tree.

What about going even further with `_partials` ?

``` bash
    ├── catalog
    │   ├── _partials
    │   │   ├── product-discount-table.tpl
    │   │   └── product-price.tpl
    │   └── product.tpl
```

@gRoussac I removed `address.tpl` from customer folder, we'll see if it fits better somewhere else.

**Comment by gabdara** [comment]
There will be many cases in which a developer wants to modify javascript. If there won't be an easy way for this many default modules will be duplicated just to make small modifications to javascript.

**Comment by alexsegura** [comment]
@Shudrum :+1: for using `partials`. Simple and beautiful. 

I really like the proposal, but I have a suggestion: why not make it _work_ first? I mean, make it work with the current directory structure, controllers, etc...
Make it work, make it right, make it fast. 

What you are proposing involves quite a lot of changes of the PrestaShop codebase, no? 
From what I imagine, more or less every pull request on this repository should come with a companion pull request from the main PrestaShop repository. 
For example if you change `AdressController` you would also change `address.tpl`.

How are you planning to manage things with Git?
Is there going to be some sort of integration branch for the StarterTheme?

---

> JavaScript is for logic, your theme probably shouldn't modify this behavior.

JavaScript is also for presentation. What if I want to make a one page webapp? 
StarterTheme shouldn't introduce more limitations. 

Developers need to be able to override _everything_ in the theme. 
Of course JavaScript code for modules should be rewritten to be more modular and not tied to CSS selectors, but still, developers should be able to rewrite everything.

**Comment by prestarocket** [comment]
Hello,

We need to be able to modify javascript files; +1 @gabdara

**Comment by gRoussac** [comment]
@alexsegura :metal: for current directory structure

**Comment by alexsegura** [comment]
@gRoussac dynamic hooks as you say have been processed during the controller phase, no?
Correct me if I'm wrong, but calling the `{hook}` function on a module that is not hooked on the position will return blank. So it's not a problem. It would have been a problem if the `{hook}` was able to "force" the execution of a hook that is not attached.

**Comment by alexsegura** [comment]
Hum, actually I'm wrong: `Hook::exec` called multiple times will actually call the method each time. 

Either the `Hook::exec` method or the `smartyHook` function should be modified to just return the output if it has been rendered before (during controller phase). This is to guarantee best performance.

**Comment by julienbourdeau** [comment]
So I removed a lot of files to keep the very minimum. The structure will evolve a lot within the next few days.
I guess we can at least start with that. Now you can install the starter theme in PrestaShop: https://github.com/PrestaShop/PrestaShop/commit/d09e0b44e4fd574e59a328ac76cdc0d04a1adb1f

**Comment by alexsegura** [comment]
I thought it was a proposal and it was open for discussion :confused:

**Comment by gRoussac** [comment]
> @gRoussac dynamic hooks as you say have been processed during the controller phase, no?

Currently they are not, then you can not test its return in the template, you have to do ugly assign tricks to test if empty like https://github.com/PrestaShop/PrestaShop/blob/develop/themes/default-bootstrap/header.tpl#L74-L83 :pouting_cat: dynamic hooks !

**Comment by alexsegura** [comment]
@gRoussac I played with that yesterday, actually this is possible with a `block` function that checks if the hook has been executed, and looks for `HOOK_*` variables in the template context, to avoid calling `Hook::exec` twice

Example:

``` smarty
{hook_isset h="displayBanner"}
<div class="banner">
  <div class="container">
    <div class="row">
    {hook h='displayBanner'}
    </div>
  </div>
</div>
{/hook_isset}
```

With the `$repeat` parameter of the callback function you can avoid rendering the block content is the return value of the hook is empty.

**Comment by gRoussac** [comment]
Whoo well you lost me there. What is hook_isset ?

Regards

**Comment by kpodemski** [comment]
I guess custom function where he check if hook is empty but to be honest I don't see advantage here :D

**Comment by gRoussac** [comment]
IMHO a view is just supposed to display, not calling the model....

**Comment by kpodemski** [comment]
I don't think we have any choice here, if something is dynamic... I guess the best way to check if hook is empty is this from @gRoussac PR, maybe there's a way to improve behaviour of Hook::exec but I don't see any possibilites for Smarty optimization

**Comment by alexsegura** [comment]
It is a custom Smarty block function that does not render its content if the hook is empty. 
But as I said it also needs another change to be able to execute a hook only once per page. 

@gRoussac it does not necessarily call the model. Another example, `{hook h="footer"}`. In this case, the `$HOOK_FOOTER` variable has been defined by `FrontController`. The `{hook}` function should be modified to just return it instead of calling `Hook::exec` again

**Comment by kpodemski** [comment]
So... we should have something like... list of executed hooks? In cache?

**Pull request merged**
